### ISSUE TITLE
bioSyntax Release TODO

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#25]
Hey team,
Our little project is really coming together! I know it's a busy time for all of coming up but I think pushing back the release deadline by a week and a half will let us finish this strong. **Wednesday December 13th** is the goal deadline.

### VanBug
On Dec 14th there is a VanBug (Vancouver Bioinformatics) meeting and 3-minute lightning talks. We can use this to let all the bioinformaticians across Vancouver know about bioSyntax and to get the word out. This is a great opportunity to put yourself out there and get to meet more of the bioinformatics community, I'm hoping one of you will be keen to represent bioSyntax.
- [x] Prepare and Give 3 minute lightning talk on bioSyntax (Alyssa)
:tada: Alyssa won 3rd place =D w00t

### [Manuscript](https://github.com/ababaian/bioSyntax/issues/13 )
This past weekend I spent a few hours going over the manuscript and I've evenly divided the remaining work. As per ICMJE, being a scientific author means you must contribute a non-trivial portion to writing and take responsibility for everything included (so proof read others work too). This needs to be done earlier then the final deadline because it's going to have to go through some revisions. Please take 3-4 hours over the next week to complete your section, they are mostly short but have to be thoughtfully written. Due: Dec 5th
- [x] Manuscript Draft Finished (All)
- [x] Compile references in google doc into one reference manager and upload library (?) 

### Tasks Remaining
- [Core Syntaxes:](https://github.com/ababaian/bioSyntax/issues/14) We are incredibly close! I can do sam-vim. Anicet is working on PDB-gedit. We need VCF-Gedit and SAM-Gedit.
- [x] VCF-sublime (German)
- [ ] PDB-gedit (Anicet)
- [x] SAM-vim (Artem)
- [x] VCF-gedit (German)
- [x] SAM-gedit (Jeff) 

- [x] Go back to all Fasta formats (Sublime / Vim / Gedit) add 16-color NT coloring (no context recog.)

### Open Bug-fixes
- [x] VCF-less ID highlighting (Artem)
- [x] VCF-less simplify last columns to speed up (Artem)
- [x] FQ-vim FQ-sublime does not work with comments on `+` line (Jasper + Artem)
- [x] BED-gedit use robust column selection ( Push to Post-Release)
- [x] FQ-gedit is incomplete (Artem)

- Testing Syntaxes: It'll be important to test all the syntaxes across ports to make sure they behave and look the same. We should assign 2 people to start going through it and looking for inconsistencies and bugs.
- [x] Tester 1 (Everyone)

- Installer: Alyssa has been leading this! Again having it done for next week would be great and we can start debugging and testing.
- [x] Complete Installer (Alyssa)
- [x] Update 'Install' instructions page with automatic installer and also manual installation instructions (Alyssa)

- Theme: We need to make full ANSI-256bit color schemes for bioSyntax, a single set of variable names, and then go through the syntax files and implement the variable names and theme. Pretty big task but can be started for the finished ports (sublime/ less).
- [X] Fill out bioSyntax.xls theme file for ANSI-256 bit, decide on one logical system for variable naming (Artem)
- [X] Go through sublime syntax files and re-name variables (Artem)
- [x] Go through less syntax files and re-name variables (Artem)
- [x] Go through vim files and re-name variables (Jasper)

- [x] Go through gedit files and re-name variables (Artem Started)

> I've made our gedit-theme `bioSyntax/syntax/gedit/bioSyntax.xml`. We need someone to go through our gedit-syntax files and change the `<styles>` section so that all colors are `map-to="bioSyntax:VARNAME"`. I've done bed.lang, clustal.lang and faidx.lang as examples 

### Meeting up
Let's take a break this week from meeting as last week went pretty long.  If you can all work independently on the thing you're assigned and the manuscript then we can meet next week to plan out the finish and do what we have to do. I think we're all a bit less busy then too.
- [x] Fill out Poll: https://dudle.inf.tu-dresden.de/bioSyntax3/

OK, I think that's the major points.If there's anything more we'd like to discuss. Please sign yourself up for tasks which don't have someone working on them (Just Edit this comment). Also do 1 thing at a time.

**Comment by fransilvion** [comment]
TODO for our installer 

- [x] - the script should output the requirements if it fails
- [x] - a warning for the 'less' installation telling user that the script is going to update his less installation, and whether he wants to proceed
- [ ] - Uninstall instructions
