### ISSUE TITLE
bioSyntax TODO -- Post-Release

### ISSUE THREAD

**Issue by ababaian** [ababaian/bioSyntax#26]
We're coming up on a few good ideas of things we should work on but don't fall into the initial release. Feel free to edit and add things here:

- [ ] Add Atomic Coloring. [JMol](http://jmol.sourceforge.net/jscolors/) / [CPK](https://en.wikipedia.org/wiki/CPK_coloring) coloring to atoms/elements when they appear in a file-format (PDB).

- [ ] Set-up Vim / Sublime / Gedit to only use bioSyntax theme when a bioSyntax format is being used; otherwise use the default or preset theme. [Sublime Example](https://hiltmon.com/blog/2012/11/07/multiple-themes-in-sublime-text-2/)

- [ ] Re-write the `bed-gedit` syntax to use 'Robust Column Selection'

- [ ] Optimize the Regex Engine for VCF -gedit -sublime -vim(?) to account for catastrophic backtracking. (See vcf-less for a fixed example)

- [ ] Secondary Color Gradient: In BED/WIG files where there can be a score, have one color scheme (like we have) for 0-1000 range. Have a second color gradient (orange?) which recognizes 0.0 - 1.00 (decimal scale). This will support two widely used data-ranges then 0-1 and 0-1000.

- [ ] Make 'Infographics' for complex file-types (SAM, VCF, GTF) to help users learn and intepret the file formats. Include things such as PHRED numeric scale, FLAG conversion bits, what each field is etc... Use bioSyntax theme colours as a teaching tool here.

### Installer Updates:
- [ ] The script should output the requirements if it fails; or prompt user to type in which software to install for
- [ ] For less: inform user and prompt (Y/N) for software updates and adding alias commands
- [ ] On website, include an uninstall instructions. (i.e. delete these files)
