### ISSUE TITLE
bioSyntax ToDo List Day 1

### ISSUE THREAD

**Issue by pan-chu** [ababaian/bioSyntax#5]
# Example files
- [X] upload example files to git repo

# Installer
- [ ] Windows Installer script
- [ ] Linux Installer script
- [ ] Mac Installer script

# Syntax for File Formats
- [ ] SAM, BAM: Eric
- [ ] FASTA: Anicet
- [ ] FASTQ: Jasper
- [ ] VCF: Alyssa
- [X] WIG: Artem
- [X] BED: Gherman 
- [ ] GTF: Jeffrey
- [ ] PDB
- [ ] TSV / CSV - maybe introduce ways to view these nicely in the text editor

# Color Scheme
- [ ] Define Color Scheme File
- [X] Gradient Coloring
- [ ] Full IUPAC nucleotides
- [ ] Amino Acids (various kinds)

**Comment by ababaian** [comment]
* Put together 'example files' for testing of all the different formats
